baseURL = "/"
languageCode = "en-us"
title = "omarosullivan.com"
theme = "PaperMod"
[pagination]
  pagerSize = 9

[params]
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowReadingTime = true
  displayFullLangName = true
  description = "Omar's Portfolio"
  
  # TinaCMS Configuration
  [params.tinacms]
    enable = false  # Set to true when you have TinaCMS credentials
    clientId = ""   # Will be provided by TinaCMS
    token = ""      # Will be provided by TinaCMS

[menu]
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30
