baseURL = "/"
languageCode = "en-us"
title = "omarosullivan.com"
theme = "PaperMod"
[pagination]
  pagerSize = 9

[params]
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowReadingTime = true
  displayFullLangName = true
  description = "Work, notes, and experiments."
  
  [params.assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"
    theme_color = "#007cba"
    msapplication_TileColor = "#007cba"
  
  # TinaCMS Configuration
  [params.tinacms]
    enable = false  # Set to true when you have TinaCMS credentials
    clientId = ""   # Will be provided by TinaCMS
    token = ""      # Will be provided by TinaCMS

[[menu.main]]
  name = "Sketches"
  url = "/portfolio/"
  weight = 10

[[menu.main]]
  name = "Photography"
  url = "/photography/"
  weight = 12

[[menu.main]]
  name = "Poetry"
  url = "/poetry/"
  weight = 15

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 30


[menu]
          