backend:
  name: github
  repo: oos/omarosullivan.com
  branch: main
  base_url: https://decap-oauth.netlify.app
  auth_endpoint: /oauth/authorize

site_url: https://omarosullivan.com
display_url: https://omarosullivan.com

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    per_page: 100
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "object", fields: [{ label: "Image", name: "image", widget: "image" }], required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    per_page: 100
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "config.toml"
        label: "Site Configuration"
        name: "config"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "string" }
